<?php
// Needs to be added to avoid cache problems
function paging8_preprocess_node(&$variables) {
    $variables['#cache']['contexts'][] = 'url.query_args:page';
}

use Drupal\filter\FilterProcessResult;

/**
 * Implements hook_theme().
 */
function paging8_theme() {
    return [
        'top_pager' => [
            'variables' => ['top_pager_array' => NULL],
        ],
        'bottom_pager' => [
            'variables' => ['bot_pager_array' => NULL],
        ],
        'title_list' => [
            'variables' => ['title_list_array' => NULL],
        ],
    ];
}